name: fprime-tools test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Clone fprime
        run: |
          cd test
          mkdir test_env
          cd test_env
          git clone https://github.com/nasa/fprime.git
          cd ../..
      - name: Test with pytest
        run: |
          pytest --ignore=test/test_env