name: Component Cookiecutter Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
    branches:
      - "**"
    tags-ignore:
      - "**"
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Checking Component Cookiecutter
    runs-on: ubuntu-20.04
    steps:
    - name: Setup fprime
      run: git clone https://github.com/nasa/fprime.git
    - name: Create component
      if: "!contains(github.event_name, 'pull_request')"
      run: fprime-util new --component
    - name: Create component
      if: "!contains(github.event_name, 'pull_request')"
      run: fprime-util new --component
