name: Component Cookiecutter Test
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job test an example
    steps:
    - uses: actions/checkout@v2
    - name: test example step
      uses: ./.github/actions/
      id: github-ci-action
      with:
        test: one
      # Use the output from the `hello` step
    - name: Get the completion status
      run: echo "The completion status was ${{ steps.hello.outputs.completed }}"
